name: cv
channels:
  - damianavila82
  - conda-forge
  - defaults
dependencies:
  - imageio=2.3.0=py_1
  - moviepy=0.2.3.5=py_0
  - olefile=0.45.1=py_1
  - tqdm=4.24.0=py_0
  - rise=5.3.0=py36_0
  - appdirs=1.4.3=py36h28b3542_0
  - asn1crypto=0.24.0=py36_0
  - attrs=18.1.0=py36_0
  - automat=0.7.0=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=2.1.3=py36_0
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2018.03.07=0
  - cairo=1.14.12=h8948797_3
  - certifi=2018.8.13=py36_0
  - cffi=1.11.5=py36h9745a5d_0
  - chardet=3.0.4=py36_1
  - constantly=15.1.0=py36h28b3542_0
  - cryptography=2.3=py36hb7f436b_0
  - cryptography-vectors=2.3=py36_0
  - cycler=0.10.0=py36_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py36_0
  - entrypoints=0.2.3=py36_2
  - expat=2.2.5=he0dffb1_0
  - ffmpeg=3.4=h7985aa0_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_0
  - glib=2.56.1=h000015b_0
  - gmp=6.1.2=h6c8ec71_1
  - graphite2=1.3.11=h16798f4_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.4=hec2c2bc_0
  - hdf5=1.10.2=hba1933b_1
  - html5lib=1.0.1=py36_0
  - hyperlink=18.0.0=py36_0
  - icu=58.2=h9c2bf20_1
  - idna=2.7=py36_0
  - incremental=17.5.0=py36_0
  - intel-openmp=2018.0.3=0
  - ipykernel=4.8.2=py36_0
  - ipython=6.5.0=py36_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.4.0=py36_0
  - jasper=2.0.14=h07fcdf6_1
  - jedi=0.12.1=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py36_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.1=h8fa1ad8_3
  - libopus=1.2.1=hb9ed12e_0
  - libpng=1.6.34=hb9fc6fc_0
  - libprotobuf=3.5.2=h6f1eeef_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libtiff=4.0.9=he85c1e1_1
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - markupsafe=1.0=py36h14c3975_1
  - matplotlib=2.2.3=py36hb69df0a_0
  - mistune=0.8.3=py36h14c3975_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.4=py36h4414c95_1
  - mkl_random=1.0.1=py36h4414c95_1
  - nbconvert=5.3.1=py36_0
  - nbformat=4.4.0=py36_0
  - ncurses=6.1=hf484d3e_0
  - notebook=5.6.0=py36_0
  - numpy=1.15.0=py36h1b885b7_0
  - numpy-base=1.15.0=py36h3dfced4_0
  - opencv=3.4.1=py36h6fd60c2_3
  - openssl=1.0.2p=h14c3975_0
  - pandoc=2.2.1=h629c226_0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.1=py36_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pillow=5.2.0=py36heded4f4_0
  - pip=10.0.1=py36_0
  - pixman=0.34.0=hceecf20_3
  - prometheus_client=0.3.1=py36_0
  - prompt_toolkit=1.0.15=py36_0
  - ptyprocess=0.6.0=py36_0
  - py-opencv=3.4.1=py36h8fa1ad8_3
  - pyasn1=0.4.4=py36_0
  - pyasn1-modules=0.2.2=py36_0
  - pycparser=2.18=py36_1
  - pygments=2.2.0=py36_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.2.0=py36_1
  - pysocks=1.6.8=py36_0
  - python=3.6.6=hc3d631a_0
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.5=py36_0
  - pyzmq=17.1.2=py36h14c3975_0
  - qt=5.9.6=h52aff34_0
  - qtconsole=4.3.1=py36_0
  - readline=7.0=ha6073c6_4
  - requests=2.19.1=py36_0
  - send2trash=1.5.0=py36_0
  - service_identity=17.0.0=py36h28b3542_0
  - setuptools=40.0.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.8=py36hf484d3e_0
  - six=1.11.0=py36_1
  - sqlite=3.24.0=h84994c4_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36_0
  - tk=8.6.7=hc745277_3
  - tornado=5.1=py36h14c3975_0
  - traitlets=4.3.2=py36_0
  - twisted=18.7.0=py36h14c3975_1
  - urllib3=1.23=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - wheel=0.31.1=py36_0
  - widgetsnbextension=3.4.0=py36_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=hf484d3e_0
  - zlib=1.2.11=ha838bed_2
  - zope=1.0=py36_0
  - zope.interface=4.5.0=py36h14c3975_0
  - pip:
    - jupyter-contrib-nbextensions
